name: Deploy Website to GitHub Pages

on:
  workflow_run:
    workflows: ["HTML Lint Check"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: . # Deploy all files in repo root (index.html)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
