name: Deploy Pages

on:
  workflow_run:
    workflows: ["HTML Lint Check"]
    types: [completed]

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo "Building site..."
      - name: Deploy
        uses: actions/deploy-pages@v4
