name: Run Unit Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Clean node_modules
        run: rm -rf node_modules

      - name: Install dependencies (CI mode)
        run: npm ci

      - name: Run Tests
        run: npm test
